"""Bootstrap logic for `salt-cisco-mcp install`."""
from __future__ import annotations

import shutil
import textwrap
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class InstallResult:
    success: bool
    created_dirs: list[str] = field(default_factory=list)
    config_file: str = ""
    warnings: list[str] = field(default_factory=list)


_CONFIG_TEMPLATE = textwrap.dedent(
    """\
    # salt-cisco-mcp configuration
    # Generated by `salt-cisco-mcp install`
    # Edit to match your environment.

    server:
      transport: http
      http_host: "127.0.0.1"
      http_port: 7842
      allow_write: false

    paths:
      doc_db: "{data_dir}/docs.db"
      log_file: "{log_dir}/server.log"
      audit_log: "{audit_dir}/audit.jsonl"
      live_cache: "{data_dir}/live-cache"

    salt_master:
      salt_call_path: salt-call
      salt_key_path: salt-key
      command_timeout_s: 30

    security:
      http_auth:
        mode: bearer
        bearer_token_file: "{config_dir}/bearer.token"
      bind_local_only: true

    telemetry:
      enabled: true
      metrics_dir: "{data_dir}"
    """
)


def install_logic(
    config_dir: str,
    data_dir: str,
    log_dir: str,
    audit_dir: str,
    salt_call_cmd: str = "salt-call",
    dry_run: bool = False,
) -> InstallResult:
    """Create directories and write a default config.yaml.

    Returns an InstallResult describing what was (or would be) created.
    """
    dirs = [config_dir, data_dir, log_dir, audit_dir]
    result = InstallResult(success=True, created_dirs=list(dirs))

    if not shutil.which(salt_call_cmd):
        result.warnings.append(
            f"salt-call not found: '{salt_call_cmd}' is not on PATH. "
            "Install salt-minion and ensure salt-call is accessible."
        )

    if dry_run:
        return result

    for d in dirs:
        Path(d).mkdir(parents=True, exist_ok=True)

    cfg_path = Path(config_dir) / "config.yaml"
    if not cfg_path.exists():
        content = _CONFIG_TEMPLATE.format(
            config_dir=config_dir,
            data_dir=data_dir,
            log_dir=log_dir,
            audit_dir=audit_dir,
        )
        cfg_path.write_text(content, encoding="utf-8")
        result.config_file = str(cfg_path)

    return result
